app/models.py
from app import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    latitude = db.Column(db.Float, nullable=False)
    longitude = db.Column(db.Float, nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

class Crop(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    name = db.Column(db.String(150),nullable=False)
    date_planted = db.Column(db.Date, nullable = False)
    soil_type = db.Column(db.String(150), nullable=False)

    user = db.relationship('User', backref=db.backref('crops', lazy=True))

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'key here'  #Generate and add a Secret key here when deploying
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///krishirakshak.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)


    from app import routes
    app.register_blueprint(routes.bp)

    # Initialize login manager
    login_manager = LoginManager()
    login_manager.login_view = 'routes.login'
    login_manager.login_message = "Please log in first"
    login_manager.login_message_category = 'warning' 
    login_manager.init_app(app)

    from app.models import User  # simple user model
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id)) 

    return app

app/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from app.models import User,Crop
from app import db
from datetime import datetime
from fastmcp import Client
from fastmcp.client.transports import StreamableHttpTransport


transport = StreamableHttpTransport("http://127.0.0.1:8000/mcp")

# Create the client
mcp_client = Client(name="CropDiseasePredictor", transport=transport)
bp = Blueprint('routes', __name__,template_folder='template',static_folder='static')

@bp.route('/')
@bp.route('/home')
def home():
    print("Server Started") 
    return render_template('index.html')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username).first()
        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for('routes.dashboard'))  #LOGGED IN 
        flash('Invalid username or password', 'danger')
    return render_template('login.html')

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('routes.login'))


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        retype_password = request.form['password_confirm']
        latitude = request.form.get('latitude')
        longitude = request.form.get('longitude')

        if not latitude or not longitude:
            flash('Field location is required.', 'danger')
            return render_template('signup.html')
        if password != retype_password:
            flash('Passwords do not match', 'danger')
        elif User.query.filter_by(username=username).first():
            flash('Username already exists', 'danger')
        else:
            new_user = User(
                username=username,
                latitude=float(latitude),
                longitude=float(longitude)
                )
            new_user.set_password(password)
            db.session.add(new_user)
            db.session.commit()
            flash('Account created successfully!', 'success')
            return redirect(url_for('routes.login'))

    return render_template('signup.html')

@bp.route('/dashboard')
@login_required
async def dashboard():
    crops = Crop.query.filter_by(user_id=current_user.id).order_by(Crop.date_planted.desc()).all()

    crop_data = []
    async with mcp_client:
        for crop in crops:
            age_days = (datetime.utcnow().date() - crop.date_planted).days
            result = await mcp_client.call_tool(
                "get_crop_points",
                { 
                    "crop_name": crop.name, 
                    "age_days": age_days, 
                    "soil_type": crop.soil_type, 
                    "lat": current_user.latitude, 
                    "lon": current_user.longitude 
                }
            )

             # Extract the text from the MCP result
            raw_text = result.data if hasattr(result, "data") else str(result)
            
            # Split the returned info to separate disease, temp, humidity
            lines = raw_text.split("\n")
            disease_line = lines[0] if len(lines) > 0 else ""
            temp_line = lines[1].split(",")[0] if len(lines) > 1 else ""
            humidity_line = lines[1].split(",")[1] if len(lines) > 1 else ""
            soil_line = f"🟫 Soil Type: {crop.soil_type}"

            # Join all lines vertically with <br> for HTML
            points_text = (
                    f"<li>{disease_line}</li><br>"
                    f"<li>{soil_line}</li>"
                    f"<li>{temp_line}</li>"
                    f"<li>{humidity_line}</li>"
                )
            
            crop_data.append({
                'id': crop.id,
                'name': crop.name,
                'soil_type': crop.soil_type,
                'age_days': age_days,
                'points' : points_text
            })

    return render_template('dashboard.html', crops=crop_data)

@bp.route('/add_crop', methods=['GET', 'POST'])
@login_required
def add_crop():
    if request.method == 'POST':
        name = request.form['name']
        date_str = request.form['date_planted']
        soil_type = request.form['soil_type']

        try:
            date_planted = datetime.strptime(date_str, '%Y-%m-%d').date()
            new_crop = Crop(
                user_id = current_user.id,
                name = name,
                date_planted =date_planted,
                soil_type=soil_type
            )
            db.session.add(new_crop)
            db.session.commit()
            flash('Crop added successfully!', 'success')
            return redirect(url_for('routes.dashboard'))
        except ValueError:
            flash('Invalid date format. Use YYYY-MM-DD.', 'danger')
    return render_template('add_crop.html')

@bp.route('/delete_crop/<int:crop_id>', methods=['POST'])
@login_required
def delete_crop(crop_id):
    crop = Crop.query.get_or_404(crop_id)
    if crop.user_id != current_user.id:
        flash('You cannot delete this crop.', 'danger')
        return redirect(url_for('routes.dashboard'))

    db.session.delete(crop)
    db.session.commit()
    flash('Crop deleted successfully!', 'success')
    return redirect(url_for('routes.dashboard'))

app/templates/add_crop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Crop | KrishiRakshak</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <nav class="navbar">
        <div class="logo">KrishiRakshak</div>
        <ul class="nav-links">
            <li><a href="{{ url_for('routes.dashboard') }}">Dashboard</a></li>
            <li><a href="{{ url_for('routes.logout') }}">Logout</a></li>
        </ul>
    </nav>

    <div class="login-container">
        <h2>Add Crop</h2>
        <form method="POST">
            <input type="text" name="name" placeholder="Crop Name" required>
            <input type="date" name="date_planted" required>
            <select name="soil_type" required>
                <option value="" disabled selected>Select Soil Type</option>
                <option value="Clay">Clay</option>
                <option value="Loamy">Loamy</option>
                <option value="Sandy">Sandy</option>
                <option value="Silty">Silty</option>
                <option value="Peaty">Peaty/Organic-rich</option>
                <option value="Soft">Soft/Light</option>
            </select>
            <button type="submit">Add Crop</button>
        </form>
    </div>
</body>
</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard | KrishiRakshak</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <nav class="navbar">
        <div class="logo">KrishiRakshak</div>
        <ul class="nav-links">
            <li><a href="{{ url_for('routes.logout') }}">Logout</a></li>
        </ul>
    </nav>

    <div class="dashboard-header">
        <h2>Dashboard</h2>
        <a href="{{ url_for('routes.add_crop') }}" class="btn">+ Add Crops</a>
    </div>

    <div class="dashboard-content">
        {% if crops %}
        <ul class="crop-list">
            {% for crop in crops %}
            <li class="crop-item">
                <div class="crop-header">
                    <strong>{{ crop.name }}</strong>
                    <span class="crop-age">[Age: {{ crop.age_days }} days]</span>
                    <form method="POST" action="{{ url_for('routes.delete_crop', crop_id=crop.id) }}" onsubmit="return confirm('Are you sure you want to delete this crop?');">
                        <button type="submit" class="btn-delete">×</button>
                    </form>
                </div>
                <ul class="crop-details">
                    <li>{{ crop.points|safe }}</li>
                </ul>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No crops added yet. Click +Add Crops to start!</p>
        {% endif %}
    </div>
    <script>
        window.addEventListener('load', () => {
        const cards = document.querySelectorAll('.crop-item');
        let maxWidth = 0;

        cards.forEach(card => {
            const cardWidth = card.offsetWidth;
            if (cardWidth > maxWidth) maxWidth = cardWidth;
        });

        cards.forEach(card => {
            card.style.width = maxWidth + 'px';
        });
        });
    </script>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>KrishiRakshak</title>
  <link rel="stylesheet" href="{{ url_for('static',filename='style.css') }}">
</head>

<body>
    <nav class="navbar">
        <div class="logo">KrishiRakshak</div>
        <ul class="nav-links">
            <li><a href="{{ url_for('routes.home') }}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{{ url_for('routes.login') }}">Login/Signup</a></li>
        </ul>
    </nav>

    <div class="content">
        <h1>Welcome to Krishi Rakshak</h1>
        <p>The Protector of Your Crops</p>
        <a href="{{ url_for('routes.login') }}" class="btn">Login to get started</a>
    </div>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login | KrishiRakshak</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <nav class="navbar">
        <div class="logo">KrishiRakshak</div>
        <ul class="nav-links">
            <li><a href="{{ url_for('routes.home') }}">Home</a></li>
            <li><a href="{{ url_for('routes.signup') }}" >Signup</a></li>
        </ul>
    </nav>

    <div class="login-container">
        <h2>Login</h2>

        <form method="POST" action="/login">
            <input type="text" name="username" placeholder="Username" required>
            <input type="password" name="password" placeholder="Password" required>
            <button type="submit">Login</button>
        </form>
        <p class="signup-text">Don't have an account? <a href="{{ url_for('routes.signup') }}">Sign up</a></p>
    </div>
</body>
</html>

app/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login | KrishiRakshak</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <nav class="navbar">
        <div class="logo">KrishiRakshak</div>
        <ul class="nav-links">
            <li><a href="{{ url_for('routes.home') }}">Home</a></li>
            <li><a href="{{ url_for('routes.login') }}" >Login</a></li>
        </ul>
    </nav>

    <div class="login-container">
        <h2>Login</h2>
        <form method="POST" action="/signup">
            <input type="text" name="username" placeholder="Username" required>
            <input type="password" name="password" placeholder="Password" required>
            <input type="password" name="password_confirm" placeholder="Retype Password" required> 
            
            <input type="hidden" name="latitude" id="latitude">
            <input type="hidden" name="longitude" id="longitude">      

            <button type="submit" id="signup-button" disabled>Signup</button>
        </form>
        <p class="signup-text">Already have an account? <a href="{{ url_for('routes.login') }}">Log In</a></p>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const signupButton = document.getElementById('signup-button');

            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition((position) => {
                    document.getElementById('latitude').value = position.coords.latitude;
                    document.getElementById('longitude').value = position.coords.longitude;
                    signupButton.disabled = false; // enable submit once location is available
                }, (error) => {
                    alert('Field location is required. Please allow location access.');
                });
            } else {
                alert('Geolocation not supported by browser. Field location is required.');
            }
        });
    </script>
</body>
</html>